/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;


import java.util.Date;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.IzinIstek;
import model.Kullanici;



public class KullaniciEkranFrame5 extends javax.swing.JFrame {

    private String girisYapanKullaniciAdi,girisYapanKullaniciK_adi;
    private Kullanici girisYapanKullanici;
   
    private Kullanici girisYapaniGetir=new Kullanici();
    
    DefaultTableModel model=new DefaultTableModel();
 
   
    
    
    public KullaniciEkranFrame5() {
        initComponents();
        
        
    }

    KullaniciEkranFrame5(String gelenKullaniciAdi) {
        initComponents();
        girisYapanKullaniciAdi=gelenKullaniciAdi;
        
        girisYapanKullanici=girisYapaniGetir.sistemdekiKullaniciyiGetir(girisYapanKullaniciAdi);
        
        
       anasayfaBilgileriniGetir();
       
       
        
        
       
        
        
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu3 = new javax.swing.JMenu();
        KullaniciEkranIzinIstegiYapDialog = new javax.swing.JDialog();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        kullaniciEkranIzinisteIstekGonderButon = new javax.swing.JButton();
        izinIstekBaslangicDateChooser = new com.toedter.calendar.JCalendar();
        izinIstekBitisDateChooser = new com.toedter.calendar.JCalendar();
        izinTurYillik = new javax.swing.JRadioButton();
        izinTurMazeret = new javax.swing.JRadioButton();
        izinTurRapor = new javax.swing.JRadioButton();
        izinTurUcretsiz = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        kullaniciEkranIzinisteklerimDialog = new javax.swing.JDialog();
        jScrollPane1 = new javax.swing.JScrollPane();
        kullaniciEkranIzinisteklerimDialogTablo = new javax.swing.JTable();
        jLabel19 = new javax.swing.JLabel();
        kullaniciEkranBilgilerimiGuncelleDialog = new javax.swing.JDialog();
        kullaniciEkranGuncelleAdtxt = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        kullaniciEkranGuncelleSoyAdtxt = new javax.swing.JTextField();
        kullaniciEkranGuncelleBirimtxt = new javax.swing.JTextField();
        kullaniciEkranGuncelleKullaniciAditxt = new javax.swing.JTextField();
        kullaniciEkranGuncelleSifretxt = new javax.swing.JTextField();
        kullaniciEkranGuncelleGuncelleYapButon = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        kullaniciEkranGuncelleDogumTarrihitxt = new javax.swing.JTextField();
        kullaniciEkranGuncelleCinsiyettxt = new javax.swing.JTextField();
        kullaniciEkranGuncelleSehirtxt = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        kullaniciEkran5HosgeldinizLabel = new javax.swing.JLabel();
        kullaniciEkran5AdLabel = new javax.swing.JLabel();
        kullaniciEkran5SoyadLabel = new javax.swing.JLabel();
        kullaniciEkran5CinsiyetLabel = new javax.swing.JLabel();
        kullaniciEkran5BirimLabel = new javax.swing.JLabel();
        kullaniciEkran5DogumTarihiLabel = new javax.swing.JLabel();
        kullaniciEkran5TCLabel = new javax.swing.JLabel();
        kullaniciEkran5KalanizinLabel = new javax.swing.JLabel();
        kullaniciEkran5KullanilanizinLabel = new javax.swing.JLabel();
        kullaniciEkranCikisGeriButon = new javax.swing.JButton();
        kullaniciEkran5SifreLabel = new javax.swing.JLabel();
        kullaniciEkran5KullaniciAdiLabel = new javax.swing.JLabel();
        kullaniciEkran5SehirLabel = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        kullaniciEkranIzinistegiMenu = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        kullaiciEkranIzinisteklerimMenu = new javax.swing.JMenuItem();
        kullaiciEkranBilgilerimiGuncelleMenu = new javax.swing.JMenuItem();

        jMenu3.setText("jMenu3");

        KullaniciEkranIzinIstegiYapDialog.setMinimumSize(new java.awt.Dimension(800, 600));
        KullaniciEkranIzinIstegiYapDialog.setPreferredSize(new java.awt.Dimension(800, 600));

        jLabel12.setText("İzin başlangç");

        jLabel13.setText("İzin Bitiş");

        kullaniciEkranIzinisteIstekGonderButon.setText("İsteği Gönder");
        kullaniciEkranIzinisteIstekGonderButon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kullaniciEkranIzinisteIstekGonderButonActionPerformed(evt);
            }
        });

        izinTurYillik.setText("Yıllık");
        izinTurYillik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                izinTurYillikActionPerformed(evt);
            }
        });

        izinTurMazeret.setText("Mazeret");
        izinTurMazeret.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                izinTurMazeretActionPerformed(evt);
            }
        });

        izinTurRapor.setText("Rapor");
        izinTurRapor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                izinTurRaporActionPerformed(evt);
            }
        });

        izinTurUcretsiz.setText("Ücretsiz");
        izinTurUcretsiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                izinTurUcretsizActionPerformed(evt);
            }
        });

        jLabel1.setText("İzin Türü");

        javax.swing.GroupLayout KullaniciEkranIzinIstegiYapDialogLayout = new javax.swing.GroupLayout(KullaniciEkranIzinIstegiYapDialog.getContentPane());
        KullaniciEkranIzinIstegiYapDialog.getContentPane().setLayout(KullaniciEkranIzinIstegiYapDialogLayout);
        KullaniciEkranIzinIstegiYapDialogLayout.setHorizontalGroup(
            KullaniciEkranIzinIstegiYapDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(KullaniciEkranIzinIstegiYapDialogLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(KullaniciEkranIzinIstegiYapDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13))
                .addGap(44, 44, 44)
                .addGroup(KullaniciEkranIzinIstegiYapDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(KullaniciEkranIzinIstegiYapDialogLayout.createSequentialGroup()
                        .addComponent(izinIstekBitisDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(215, Short.MAX_VALUE))
                    .addGroup(KullaniciEkranIzinIstegiYapDialogLayout.createSequentialGroup()
                        .addComponent(izinIstekBaslangicDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(KullaniciEkranIzinIstegiYapDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, KullaniciEkranIzinIstegiYapDialogLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(55, 55, 55))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, KullaniciEkranIzinIstegiYapDialogLayout.createSequentialGroup()
                                .addGroup(KullaniciEkranIzinIstegiYapDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(izinTurYillik)
                                    .addComponent(izinTurMazeret)
                                    .addComponent(izinTurRapor)
                                    .addComponent(izinTurUcretsiz))
                                .addGap(44, 44, 44))))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, KullaniciEkranIzinIstegiYapDialogLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(kullaniciEkranIzinisteIstekGonderButon)
                .addGap(312, 312, 312))
        );
        KullaniciEkranIzinIstegiYapDialogLayout.setVerticalGroup(
            KullaniciEkranIzinIstegiYapDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(KullaniciEkranIzinIstegiYapDialogLayout.createSequentialGroup()
                .addGroup(KullaniciEkranIzinIstegiYapDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(KullaniciEkranIzinIstegiYapDialogLayout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(jLabel12))
                    .addGroup(KullaniciEkranIzinIstegiYapDialogLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(KullaniciEkranIzinIstegiYapDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(izinIstekBaslangicDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(KullaniciEkranIzinIstegiYapDialogLayout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(izinTurYillik)
                                .addGap(18, 18, 18)
                                .addComponent(izinTurMazeret)
                                .addGap(18, 18, 18)
                                .addComponent(izinTurRapor)
                                .addGap(18, 18, 18)
                                .addComponent(izinTurUcretsiz)))))
                .addGroup(KullaniciEkranIzinIstegiYapDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(KullaniciEkranIzinIstegiYapDialogLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(izinIstekBitisDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(KullaniciEkranIzinIstegiYapDialogLayout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(jLabel13)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(kullaniciEkranIzinisteIstekGonderButon)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        kullaniciEkranIzinisteklerimDialog.setMinimumSize(new java.awt.Dimension(865, 536));

        kullaniciEkranIzinisteklerimDialogTablo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "TC", "Ad", "Soyad", "İzin Başvurusu", "Durumu"
            }
        ));
        jScrollPane1.setViewportView(kullaniciEkranIzinisteklerimDialogTablo);

        jLabel19.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel19.setText("İzin isteklerim");

        javax.swing.GroupLayout kullaniciEkranIzinisteklerimDialogLayout = new javax.swing.GroupLayout(kullaniciEkranIzinisteklerimDialog.getContentPane());
        kullaniciEkranIzinisteklerimDialog.getContentPane().setLayout(kullaniciEkranIzinisteklerimDialogLayout);
        kullaniciEkranIzinisteklerimDialogLayout.setHorizontalGroup(
            kullaniciEkranIzinisteklerimDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kullaniciEkranIzinisteklerimDialogLayout.createSequentialGroup()
                .addGap(292, 292, 292)
                .addComponent(jLabel19)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(kullaniciEkranIzinisteklerimDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 853, Short.MAX_VALUE)
                .addContainerGap())
        );
        kullaniciEkranIzinisteklerimDialogLayout.setVerticalGroup(
            kullaniciEkranIzinisteklerimDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kullaniciEkranIzinisteklerimDialogLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel19)
                .addGap(42, 42, 42)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(93, Short.MAX_VALUE))
        );

        kullaniciEkranBilgilerimiGuncelleDialog.setMinimumSize(new java.awt.Dimension(433, 532));

        jLabel10.setText("Ad");

        jLabel14.setText("Soyad");

        jLabel15.setText("Birim");

        jLabel16.setText("Kullanıcı Adı");

        jLabel17.setText("Şifre");

        kullaniciEkranGuncelleKullaniciAditxt.setText("Değiştirilemez");
        kullaniciEkranGuncelleKullaniciAditxt.setEnabled(false);

        kullaniciEkranGuncelleGuncelleYapButon.setText("Güncelle");
        kullaniciEkranGuncelleGuncelleYapButon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kullaniciEkranGuncelleGuncelleYapButonActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel18.setText("Bilgilerim");

        jLabel20.setText("Şehir");

        jLabel21.setText("Doğum Tarihi");

        jLabel22.setText("Cinsiyet");

        javax.swing.GroupLayout kullaniciEkranBilgilerimiGuncelleDialogLayout = new javax.swing.GroupLayout(kullaniciEkranBilgilerimiGuncelleDialog.getContentPane());
        kullaniciEkranBilgilerimiGuncelleDialog.getContentPane().setLayout(kullaniciEkranBilgilerimiGuncelleDialogLayout);
        kullaniciEkranBilgilerimiGuncelleDialogLayout.setHorizontalGroup(
            kullaniciEkranBilgilerimiGuncelleDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kullaniciEkranBilgilerimiGuncelleDialogLayout.createSequentialGroup()
                .addContainerGap(179, Short.MAX_VALUE)
                .addGroup(kullaniciEkranBilgilerimiGuncelleDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kullaniciEkranBilgilerimiGuncelleDialogLayout.createSequentialGroup()
                        .addComponent(kullaniciEkranGuncelleGuncelleYapButon)
                        .addGap(165, 165, 165))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kullaniciEkranBilgilerimiGuncelleDialogLayout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addGap(170, 170, 170))))
            .addGroup(kullaniciEkranBilgilerimiGuncelleDialogLayout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addGroup(kullaniciEkranBilgilerimiGuncelleDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kullaniciEkranBilgilerimiGuncelleDialogLayout.createSequentialGroup()
                        .addGroup(kullaniciEkranBilgilerimiGuncelleDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(kullaniciEkranBilgilerimiGuncelleDialogLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel10))
                            .addComponent(jLabel16)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15)
                            .addComponent(jLabel17))
                        .addGap(18, 18, 18)
                        .addGroup(kullaniciEkranBilgilerimiGuncelleDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kullaniciEkranBilgilerimiGuncelleDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(kullaniciEkranGuncelleSifretxt, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(kullaniciEkranGuncelleKullaniciAditxt, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(kullaniciEkranGuncelleAdtxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(kullaniciEkranGuncelleSoyAdtxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(kullaniciEkranGuncelleBirimtxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(kullaniciEkranBilgilerimiGuncelleDialogLayout.createSequentialGroup()
                        .addGroup(kullaniciEkranBilgilerimiGuncelleDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel22)
                            .addComponent(jLabel21)
                            .addComponent(jLabel20))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(kullaniciEkranBilgilerimiGuncelleDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(kullaniciEkranGuncelleSehirtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(kullaniciEkranGuncelleCinsiyettxt, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(kullaniciEkranGuncelleDogumTarrihitxt, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        kullaniciEkranBilgilerimiGuncelleDialogLayout.setVerticalGroup(
            kullaniciEkranBilgilerimiGuncelleDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kullaniciEkranBilgilerimiGuncelleDialogLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(kullaniciEkranBilgilerimiGuncelleDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addGroup(kullaniciEkranBilgilerimiGuncelleDialogLayout.createSequentialGroup()
                        .addComponent(kullaniciEkranGuncelleAdtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(kullaniciEkranBilgilerimiGuncelleDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(kullaniciEkranGuncelleSoyAdtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14))
                        .addGap(26, 26, 26)
                        .addGroup(kullaniciEkranBilgilerimiGuncelleDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(kullaniciEkranGuncelleBirimtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15))
                        .addGap(24, 24, 24)
                        .addGroup(kullaniciEkranBilgilerimiGuncelleDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(kullaniciEkranGuncelleKullaniciAditxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16))
                        .addGap(18, 18, 18)
                        .addGroup(kullaniciEkranBilgilerimiGuncelleDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(kullaniciEkranGuncelleSifretxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17))))
                .addGap(18, 18, 18)
                .addGroup(kullaniciEkranBilgilerimiGuncelleDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kullaniciEkranBilgilerimiGuncelleDialogLayout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addGap(32, 32, 32)
                        .addComponent(jLabel22)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel20))
                    .addGroup(kullaniciEkranBilgilerimiGuncelleDialogLayout.createSequentialGroup()
                        .addComponent(kullaniciEkranGuncelleDogumTarrihitxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(kullaniciEkranGuncelleCinsiyettxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(kullaniciEkranGuncelleSehirtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                .addComponent(kullaniciEkranGuncelleGuncelleYapButon)
                .addGap(23, 23, 23))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        kullaniciEkran5HosgeldinizLabel.setText("Hoş geldiniz, bla bla bla...");

        kullaniciEkran5AdLabel.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        kullaniciEkran5AdLabel.setText("İsim : bla bla");

        kullaniciEkran5SoyadLabel.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        kullaniciEkran5SoyadLabel.setText("Soyisim : bla bla");

        kullaniciEkran5CinsiyetLabel.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        kullaniciEkran5CinsiyetLabel.setText("Cinsiyet : bla bla");

        kullaniciEkran5BirimLabel.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        kullaniciEkran5BirimLabel.setText("Birim : ...");

        kullaniciEkran5DogumTarihiLabel.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        kullaniciEkran5DogumTarihiLabel.setText("Doğum tarihi");

        kullaniciEkran5TCLabel.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        kullaniciEkran5TCLabel.setText("TC");

        kullaniciEkran5KalanizinLabel.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        kullaniciEkran5KalanizinLabel.setText("Kalan izin :");

        kullaniciEkran5KullanilanizinLabel.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        kullaniciEkran5KullanilanizinLabel.setText("Kullanılan izin :");

        kullaniciEkranCikisGeriButon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resimler/exiticon.png_48x48.png"))); // NOI18N
        kullaniciEkranCikisGeriButon.setText("Çıkış Yap");
        kullaniciEkranCikisGeriButon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kullaniciEkranCikisGeriButonActionPerformed(evt);
            }
        });

        kullaniciEkran5SifreLabel.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        kullaniciEkran5SifreLabel.setText("Şifre");

        kullaniciEkran5KullaniciAdiLabel.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        kullaniciEkran5KullaniciAdiLabel.setText("Kullanici adi");

        kullaniciEkran5SehirLabel.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        kullaniciEkran5SehirLabel.setText("Şehir");

        jMenu1.setText("Yeni");

        kullaniciEkranIzinistegiMenu.setText("İzin isteği");
        kullaniciEkranIzinistegiMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kullaniciEkranIzinistegiMenuActionPerformed(evt);
            }
        });
        jMenu1.add(kullaniciEkranIzinistegiMenu);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Kullanıcı");

        kullaiciEkranIzinisteklerimMenu.setText("İzin isteklerim");
        kullaiciEkranIzinisteklerimMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kullaiciEkranIzinisteklerimMenuActionPerformed(evt);
            }
        });
        jMenu2.add(kullaiciEkranIzinisteklerimMenu);

        kullaiciEkranBilgilerimiGuncelleMenu.setText("Bilgilerimi güncelle");
        kullaiciEkranBilgilerimiGuncelleMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kullaiciEkranBilgilerimiGuncelleMenuActionPerformed(evt);
            }
        });
        jMenu2.add(kullaiciEkranBilgilerimiGuncelleMenu);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(kullaniciEkran5SoyadLabel)
                        .addComponent(kullaniciEkran5AdLabel)
                        .addComponent(kullaniciEkran5CinsiyetLabel)
                        .addComponent(kullaniciEkran5TCLabel)
                        .addComponent(kullaniciEkran5SehirLabel)
                        .addComponent(kullaniciEkran5DogumTarihiLabel)
                        .addComponent(kullaniciEkran5BirimLabel)
                        .addComponent(kullaniciEkran5KullaniciAdiLabel)
                        .addComponent(kullaniciEkran5SifreLabel))
                    .addComponent(kullaniciEkran5HosgeldinizLabel))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 255, Short.MAX_VALUE)
                        .addComponent(kullaniciEkranCikisGeriButon)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(kullaniciEkran5KullanilanizinLabel)
                            .addComponent(kullaniciEkran5KalanizinLabel))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(kullaniciEkran5HosgeldinizLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(kullaniciEkranCikisGeriButon)))
                .addGap(10, 10, 10)
                .addComponent(kullaniciEkran5TCLabel)
                .addGap(31, 31, 31)
                .addComponent(kullaniciEkran5AdLabel)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(kullaniciEkran5SoyadLabel)
                        .addGap(5, 5, 5)
                        .addComponent(kullaniciEkran5KullanilanizinLabel)
                        .addGap(10, 10, 10)
                        .addComponent(kullaniciEkran5CinsiyetLabel)
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(kullaniciEkran5DogumTarihiLabel)
                            .addComponent(kullaniciEkran5KalanizinLabel))
                        .addGap(33, 33, 33)
                        .addComponent(kullaniciEkran5BirimLabel)
                        .addGap(28, 28, 28)
                        .addComponent(kullaniciEkran5KullaniciAdiLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(kullaniciEkran5SifreLabel)
                        .addGap(31, 31, 31)))
                .addComponent(kullaniciEkran5SehirLabel)
                .addGap(46, 46, 46))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void kullaniciEkranCikisGeriButonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kullaniciEkranCikisGeriButonActionPerformed
        AcilisFrame1 aa=new AcilisFrame1();
        aa.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_kullaniciEkranCikisGeriButonActionPerformed

    private void kullaniciEkranIzinistegiMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kullaniciEkranIzinistegiMenuActionPerformed
       KullaniciEkranIzinIstegiYapDialog.setVisible(true);
    }//GEN-LAST:event_kullaniciEkranIzinistegiMenuActionPerformed

    private void kullaiciEkranIzinisteklerimMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kullaiciEkranIzinisteklerimMenuActionPerformed
       kullaniciEkranIzinisteklerimDialog.setVisible(true);
       //tabloyu doldur, sadece kendi izin başvurularını görebilsin.
      
       IzinIstek izinTabloDoldurma=new IzinIstek();
       model=izinTabloDoldurma.izinIstekTablosunuDoldur(girisYapanKullanici.getTc_no());
        kullaniciEkranIzinisteklerimDialogTablo.setModel(model);
       
        
    }//GEN-LAST:event_kullaiciEkranIzinisteklerimMenuActionPerformed

    private void kullaiciEkranBilgilerimiGuncelleMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kullaiciEkranBilgilerimiGuncelleMenuActionPerformed
        kullaniciEkranBilgilerimiGuncelleDialog.setVisible(true);
        kullaniciEkranGuncelleAdtxt.setText(girisYapanKullanici.getAd());
        kullaniciEkranGuncelleSoyAdtxt.setText(girisYapanKullanici.getSoyad());
        kullaniciEkranGuncelleKullaniciAditxt.setText(girisYapanKullanici.getK_adi());
        kullaniciEkranGuncelleSifretxt.setText(girisYapanKullanici.getSifre());
        kullaniciEkranGuncelleBirimtxt.setText(girisYapanKullanici.getBirim());
        kullaniciEkranGuncelleSehirtxt.setText(girisYapanKullanici.getSehir());
        kullaniciEkranGuncelleCinsiyettxt.setText(girisYapanKullanici.getCinsiyet());
        kullaniciEkranGuncelleDogumTarrihitxt.setText(girisYapanKullanici.getDogum_tarihi());
    }//GEN-LAST:event_kullaiciEkranBilgilerimiGuncelleMenuActionPerformed

    private void kullaniciEkranGuncelleGuncelleYapButonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kullaniciEkranGuncelleGuncelleYapButonActionPerformed
        
        boolean durum=false;
    try {
            Kullanici kullaniciyiGuncelle=new Kullanici();
        kullaniciyiGuncelle.setAd(kullaniciEkranGuncelleAdtxt.getText());
        kullaniciyiGuncelle.setSoyad(kullaniciEkranGuncelleSoyAdtxt.getText());
        kullaniciyiGuncelle.setK_adi(kullaniciEkranGuncelleKullaniciAditxt.getText());
        kullaniciyiGuncelle.setSifre(kullaniciEkranGuncelleSifretxt.getText());
        kullaniciyiGuncelle.setBirim(kullaniciEkranGuncelleBirimtxt.getText());
        kullaniciyiGuncelle.setSehir(kullaniciEkranGuncelleSehirtxt.getText());
        kullaniciyiGuncelle.setCinsiyet(kullaniciEkranGuncelleCinsiyettxt.getText());
        kullaniciyiGuncelle.setDogum_tarihi(kullaniciEkranGuncelleDogumTarrihitxt.getText());
        
        
        
        durum=kullaniciyiGuncelle.kullaniciGuncelle(kullaniciyiGuncelle,girisYapanKullanici.getK_adi());
        
        if(durum)
        {
           JOptionPane.showMessageDialog(rootPane, "Bilgileriniz başarıyla güncellendi..");
            anasayfaBilgileriniGetir();
            kullaniciEkranBilgilerimiGuncelleDialog.setVisible(false);
            
        }
        else
        {
             JOptionPane.showMessageDialog(rootPane, "Hata ! Lütfen bilgilerinizi kontrol edin.");
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(rootPane, "Hata ! Lütfen bilgilerinizi kontrol edin.");
    }
        
        
        
        
        
        
       
    }//GEN-LAST:event_kullaniciEkranGuncelleGuncelleYapButonActionPerformed

    private void kullaniciEkranIzinisteIstekGonderButonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kullaniciEkranIzinisteIstekGonderButonActionPerformed
   
        boolean durum=false;
        try {
          
            
            SimpleDateFormat ss2=new SimpleDateFormat("dd-MM-yyyy");
            
            
       String baslangicTarihi=ss2.format(izinIstekBaslangicDateChooser.getDate()).toString();
       String bitisTarihi=ss2.format(izinIstekBitisDateChooser.getDate()).toString();
       
      
       
       
       
       
      ///////////SEÇİLEN TARİHLER ARASINDAKİ FARKLI ALDIM///////
       SimpleDateFormat ss=new SimpleDateFormat("yyyy-MM-dd");
       Date d1=null;
       Date d2=null;
       
        
      
            try {
                d1=ss.parse(ss.format(izinIstekBaslangicDateChooser.getDate()));
                d2=ss.parse(ss.format(izinIstekBitisDateChooser.getDate()));
            } catch (Exception e) {
            }
       
            long fark=d2.getTime()-d1.getTime();
            long hours=fark/(60*60*1000);
            long days=hours/24;
       
            System.out.println("Fark: "+String.valueOf(days)); ///seçilen izin günü (sayısal olarak)diye bi alan oluştur tabloda..
     
        ////////////////////////////////////////77
        
        
        int a=JOptionPane.showConfirmDialog(this, "Başlangıç : "+baslangicTarihi+"\nBitiş : "+bitisTarihi+"\nDevam etmek istiyor musunuz?", "Mesaj",JOptionPane.OK_CANCEL_OPTION);
        
        if(a==0)
        {
        IzinIstek izinIstek=new IzinIstek();
        izinIstek.setTc_no(girisYapanKullanici.getTc_no());
        izinIstek.setIzin_baslangic(baslangicTarihi);
        izinIstek.setIzin_bitis(bitisTarihi);
        izinIstek.setKalan_izin(girisYapanKullanici.getKalan_izin());
        izinIstek.setKullanilan_izin(Integer.valueOf(25-girisYapanKullanici.getKalan_izin()));
        izinIstek.setIzin_sure((int)days);
        
        
        String izinTuru="Belirtilmemiş";
        
        if(izinTurYillik.isSelected())
            izinTuru=izinTurYillik.getText();
        if(izinTurUcretsiz.isSelected())
            izinTuru=izinTurUcretsiz.getText();
        if(izinTurRapor.isSelected())
            izinTuru=izinTurRapor.getText();
        if(izinTurMazeret.isSelected())
            izinTuru=izinTurMazeret.getText();
        
        izinIstek.setIzin_turu(izinTuru);
        
        durum=izinIstek.izinIstegiOlustur(izinIstek);
        if(durum)
        {
            JOptionPane.showMessageDialog(rootPane, "İzin isteğiniz oluşturuldu, yönetici tarafında onay bekliyor.");
            KullaniciEkranIzinIstegiYapDialog.setVisible(false);
            
        }
        else
            JOptionPane.showMessageDialog(rootPane, "Hata,bilgilerinizi kontrol edin.");
        
         
    }
         }
     catch (Exception e) {
         
         JOptionPane.showMessageDialog(rootPane, "Hata,bilgilerinizi kontrol edin."+e);
     }
     
       
       
        
        
    }//GEN-LAST:event_kullaniciEkranIzinisteIstekGonderButonActionPerformed

    private void izinTurYillikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_izinTurYillikActionPerformed
       izinTurRapor.setSelected(false);
       izinTurUcretsiz.setSelected(false);
       izinTurMazeret.setSelected(false);
    }//GEN-LAST:event_izinTurYillikActionPerformed

    private void izinTurMazeretActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_izinTurMazeretActionPerformed
       izinTurRapor.setSelected(false);
       izinTurUcretsiz.setSelected(false);
       izinTurYillik.setSelected(false);
    }//GEN-LAST:event_izinTurMazeretActionPerformed

    private void izinTurRaporActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_izinTurRaporActionPerformed
        izinTurYillik.setSelected(false);
       izinTurUcretsiz.setSelected(false);
       izinTurMazeret.setSelected(false);
    }//GEN-LAST:event_izinTurRaporActionPerformed

    private void izinTurUcretsizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_izinTurUcretsizActionPerformed
       izinTurRapor.setSelected(false);
       izinTurYillik.setSelected(false);
       izinTurMazeret.setSelected(false);
    }//GEN-LAST:event_izinTurUcretsizActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KullaniciEkranFrame5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KullaniciEkranFrame5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KullaniciEkranFrame5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KullaniciEkranFrame5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KullaniciEkranFrame5().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog KullaniciEkranIzinIstegiYapDialog;
    private com.toedter.calendar.JCalendar izinIstekBaslangicDateChooser;
    private com.toedter.calendar.JCalendar izinIstekBitisDateChooser;
    private javax.swing.JRadioButton izinTurMazeret;
    private javax.swing.JRadioButton izinTurRapor;
    private javax.swing.JRadioButton izinTurUcretsiz;
    private javax.swing.JRadioButton izinTurYillik;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem kullaiciEkranBilgilerimiGuncelleMenu;
    private javax.swing.JMenuItem kullaiciEkranIzinisteklerimMenu;
    private javax.swing.JLabel kullaniciEkran5AdLabel;
    private javax.swing.JLabel kullaniciEkran5BirimLabel;
    private javax.swing.JLabel kullaniciEkran5CinsiyetLabel;
    private javax.swing.JLabel kullaniciEkran5DogumTarihiLabel;
    private javax.swing.JLabel kullaniciEkran5HosgeldinizLabel;
    private javax.swing.JLabel kullaniciEkran5KalanizinLabel;
    private javax.swing.JLabel kullaniciEkran5KullaniciAdiLabel;
    private javax.swing.JLabel kullaniciEkran5KullanilanizinLabel;
    private javax.swing.JLabel kullaniciEkran5SehirLabel;
    private javax.swing.JLabel kullaniciEkran5SifreLabel;
    private javax.swing.JLabel kullaniciEkran5SoyadLabel;
    private javax.swing.JLabel kullaniciEkran5TCLabel;
    private javax.swing.JDialog kullaniciEkranBilgilerimiGuncelleDialog;
    private javax.swing.JButton kullaniciEkranCikisGeriButon;
    private javax.swing.JTextField kullaniciEkranGuncelleAdtxt;
    private javax.swing.JTextField kullaniciEkranGuncelleBirimtxt;
    private javax.swing.JTextField kullaniciEkranGuncelleCinsiyettxt;
    private javax.swing.JTextField kullaniciEkranGuncelleDogumTarrihitxt;
    private javax.swing.JButton kullaniciEkranGuncelleGuncelleYapButon;
    private javax.swing.JTextField kullaniciEkranGuncelleKullaniciAditxt;
    private javax.swing.JTextField kullaniciEkranGuncelleSehirtxt;
    private javax.swing.JTextField kullaniciEkranGuncelleSifretxt;
    private javax.swing.JTextField kullaniciEkranGuncelleSoyAdtxt;
    private javax.swing.JButton kullaniciEkranIzinisteIstekGonderButon;
    private javax.swing.JMenuItem kullaniciEkranIzinistegiMenu;
    private javax.swing.JDialog kullaniciEkranIzinisteklerimDialog;
    private javax.swing.JTable kullaniciEkranIzinisteklerimDialogTablo;
    // End of variables declaration//GEN-END:variables

    private void anasayfaBilgileriniGetir() {
        girisYapanKullanici=girisYapaniGetir.sistemdekiKullaniciyiGetir(girisYapanKullaniciAdi);
        kullaniciEkran5HosgeldinizLabel.setText("Hoş geldiniz, "+girisYapanKullanici.getAd());
        kullaniciEkran5AdLabel.setText("Adı : "+girisYapanKullanici.getAd());
        kullaniciEkran5SoyadLabel.setText("Soyadı : "+girisYapanKullanici.getSoyad());
        kullaniciEkran5TCLabel.setText("TC No : "+girisYapanKullanici.getTc_no());
        kullaniciEkran5KullaniciAdiLabel.setText("Kullanıcı Adı : "+girisYapanKullanici.getK_adi());
        kullaniciEkran5SifreLabel.setText("Şifre : "+girisYapanKullanici.getSifre());
        kullaniciEkran5BirimLabel.setText("Birimi : "+girisYapanKullanici.getBirim());
        kullaniciEkran5SehirLabel.setText("Sehir : "+girisYapanKullanici.getSehir());
        kullaniciEkran5CinsiyetLabel.setText("Cinsiyet : "+girisYapanKullanici.getCinsiyet());
        kullaniciEkran5DogumTarihiLabel.setText("Doğum Tarihi : "+girisYapanKullanici.getDogum_tarihi());
        kullaniciEkran5KalanizinLabel.setText("Kalan İzin : "+String.valueOf(girisYapanKullanici.getKalan_izin()));
        
        int kullanilanIzin=25-(girisYapanKullanici.getKalan_izin()); //zaten default olarak herkesin izin hakkı 25 olarak tanımladım.
        //burda 25 yerine izin hakkı tanımlanılabilir, sabitler classı oluşturup final olarak.
        
        kullaniciEkran5KullanilanizinLabel.setText("Kullanılan izin : "+kullanilanIzin);
    }
}
