/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.IzinIstek;
import model.Kullanici;


public class YoneticiEkran6 extends javax.swing.JFrame {

   
    DefaultTableModel model=new DefaultTableModel();
       DefaultTableModel model2Izin=new DefaultTableModel();
            
    
    public YoneticiEkran6() {
        initComponents();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        yoneticiEkranTumKullanicilarDialog = new javax.swing.JDialog();
        jScrollPane1 = new javax.swing.JScrollPane();
        yoneticiEkranTumKullaniciDialogTablo = new javax.swing.JTable();
        yoneticiEkranTumKullaniciDialogAramaButton = new javax.swing.JButton();
        yoneticiEkranTumKullaniciDialogAramatxt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        yoneticiEkranEskiizinlerDialog = new javax.swing.JDialog();
        jScrollPane2 = new javax.swing.JScrollPane();
        yoneticiEkranEskiizinlerDialogizinTablo = new javax.swing.JTable();
        yoneticiEkranEskiizinlerDialogizinAraButton = new javax.swing.JButton();
        yoneticiEkranEskiizinlerDialogIzinYillikFiltre = new javax.swing.JCheckBox();
        yoneticiEkranEskiizinlerDialogIzinMazeretFiltre = new javax.swing.JCheckBox();
        yoneticiEkranEskiizinlerDialogIzinRaporFiltre = new javax.swing.JCheckBox();
        yoneticiEkranEskiizinlerDialogIzinUcretsizFiltre = new javax.swing.JCheckBox();
        yoneticiEkranIzinistekleriDialog = new javax.swing.JDialog();
        jScrollPane3 = new javax.swing.JScrollPane();
        yoneticiEkranIzinistekleriTablo = new javax.swing.JTable();
        yoneticiEkranIzinistekleriOnaylaButon = new javax.swing.JButton();
        yoneticiEkranIzinistekleriReddetButon = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        yoneticiEkranCikisGeriButon = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        yoneticiEkranTumKullanicilarMenu = new javax.swing.JMenuItem();
        yoneticiEkranEskiIzinlerMenu = new javax.swing.JMenuItem();
        yoneticiEkranizinIstekleriMenu = new javax.swing.JMenuItem();

        yoneticiEkranTumKullanicilarDialog.setMinimumSize(new java.awt.Dimension(837, 465));

        yoneticiEkranTumKullaniciDialogTablo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(yoneticiEkranTumKullaniciDialogTablo);

        yoneticiEkranTumKullaniciDialogAramaButton.setText("Kullanıcı Ara");
        yoneticiEkranTumKullaniciDialogAramaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yoneticiEkranTumKullaniciDialogAramaButtonActionPerformed(evt);
            }
        });

        jLabel6.setText("Ad veya Soyad a göre arama yapar.");

        javax.swing.GroupLayout yoneticiEkranTumKullanicilarDialogLayout = new javax.swing.GroupLayout(yoneticiEkranTumKullanicilarDialog.getContentPane());
        yoneticiEkranTumKullanicilarDialog.getContentPane().setLayout(yoneticiEkranTumKullanicilarDialogLayout);
        yoneticiEkranTumKullanicilarDialogLayout.setHorizontalGroup(
            yoneticiEkranTumKullanicilarDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(yoneticiEkranTumKullanicilarDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(yoneticiEkranTumKullanicilarDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, yoneticiEkranTumKullanicilarDialogLayout.createSequentialGroup()
                        .addComponent(yoneticiEkranTumKullaniciDialogAramatxt, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(yoneticiEkranTumKullaniciDialogAramaButton)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addGap(0, 48, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        yoneticiEkranTumKullanicilarDialogLayout.setVerticalGroup(
            yoneticiEkranTumKullanicilarDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, yoneticiEkranTumKullanicilarDialogLayout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addGroup(yoneticiEkranTumKullanicilarDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yoneticiEkranTumKullaniciDialogAramatxt, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yoneticiEkranTumKullaniciDialogAramaButton)
                    .addComponent(jLabel6))
                .addGap(33, 33, 33)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70))
        );

        yoneticiEkranEskiizinlerDialog.setMinimumSize(new java.awt.Dimension(1138, 540));

        yoneticiEkranEskiizinlerDialogizinTablo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(yoneticiEkranEskiizinlerDialogizinTablo);

        yoneticiEkranEskiizinlerDialogizinAraButton.setText("Filtrele");
        yoneticiEkranEskiizinlerDialogizinAraButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yoneticiEkranEskiizinlerDialogizinAraButtonActionPerformed(evt);
            }
        });

        yoneticiEkranEskiizinlerDialogIzinYillikFiltre.setText("Yıllık");

        yoneticiEkranEskiizinlerDialogIzinMazeretFiltre.setText("Mazeret");

        yoneticiEkranEskiizinlerDialogIzinRaporFiltre.setText("Rapor");

        yoneticiEkranEskiizinlerDialogIzinUcretsizFiltre.setText("Ücretsiz");

        javax.swing.GroupLayout yoneticiEkranEskiizinlerDialogLayout = new javax.swing.GroupLayout(yoneticiEkranEskiizinlerDialog.getContentPane());
        yoneticiEkranEskiizinlerDialog.getContentPane().setLayout(yoneticiEkranEskiizinlerDialogLayout);
        yoneticiEkranEskiizinlerDialogLayout.setHorizontalGroup(
            yoneticiEkranEskiizinlerDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(yoneticiEkranEskiizinlerDialogLayout.createSequentialGroup()
                .addComponent(jScrollPane2)
                .addContainerGap())
            .addGroup(yoneticiEkranEskiizinlerDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(yoneticiEkranEskiizinlerDialogIzinYillikFiltre)
                .addGap(53, 53, 53)
                .addComponent(yoneticiEkranEskiizinlerDialogIzinMazeretFiltre)
                .addGap(54, 54, 54)
                .addComponent(yoneticiEkranEskiizinlerDialogIzinRaporFiltre)
                .addGap(37, 37, 37)
                .addComponent(yoneticiEkranEskiizinlerDialogIzinUcretsizFiltre)
                .addGap(18, 18, 18)
                .addComponent(yoneticiEkranEskiizinlerDialogizinAraButton)
                .addContainerGap(637, Short.MAX_VALUE))
        );
        yoneticiEkranEskiizinlerDialogLayout.setVerticalGroup(
            yoneticiEkranEskiizinlerDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, yoneticiEkranEskiizinlerDialogLayout.createSequentialGroup()
                .addContainerGap(116, Short.MAX_VALUE)
                .addGroup(yoneticiEkranEskiizinlerDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yoneticiEkranEskiizinlerDialogIzinYillikFiltre)
                    .addComponent(yoneticiEkranEskiizinlerDialogIzinMazeretFiltre)
                    .addComponent(yoneticiEkranEskiizinlerDialogIzinRaporFiltre)
                    .addComponent(yoneticiEkranEskiizinlerDialogIzinUcretsizFiltre)
                    .addComponent(yoneticiEkranEskiizinlerDialogizinAraButton))
                .addGap(36, 36, 36)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        yoneticiEkranIzinistekleriDialog.setMinimumSize(new java.awt.Dimension(663, 461));
        yoneticiEkranIzinistekleriDialog.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                yoneticiEkranIzinistekleriDialogMouseClicked(evt);
            }
        });

        yoneticiEkranIzinistekleriTablo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        yoneticiEkranIzinistekleriTablo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                yoneticiEkranIzinistekleriTabloMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(yoneticiEkranIzinistekleriTablo);

        yoneticiEkranIzinistekleriOnaylaButon.setText("Onayla");
        yoneticiEkranIzinistekleriOnaylaButon.setEnabled(false);
        yoneticiEkranIzinistekleriOnaylaButon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yoneticiEkranIzinistekleriOnaylaButonActionPerformed(evt);
            }
        });

        yoneticiEkranIzinistekleriReddetButon.setText("Reddet");
        yoneticiEkranIzinistekleriReddetButon.setEnabled(false);
        yoneticiEkranIzinistekleriReddetButon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yoneticiEkranIzinistekleriReddetButonActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel5.setText("İzin istekleri");

        javax.swing.GroupLayout yoneticiEkranIzinistekleriDialogLayout = new javax.swing.GroupLayout(yoneticiEkranIzinistekleriDialog.getContentPane());
        yoneticiEkranIzinistekleriDialog.getContentPane().setLayout(yoneticiEkranIzinistekleriDialogLayout);
        yoneticiEkranIzinistekleriDialogLayout.setHorizontalGroup(
            yoneticiEkranIzinistekleriDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, yoneticiEkranIzinistekleriDialogLayout.createSequentialGroup()
                .addContainerGap(275, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(250, 250, 250))
            .addGroup(yoneticiEkranIzinistekleriDialogLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jScrollPane3)
                .addGap(18, 18, 18)
                .addGroup(yoneticiEkranIzinistekleriDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(yoneticiEkranIzinistekleriOnaylaButon)
                    .addComponent(yoneticiEkranIzinistekleriReddetButon))
                .addGap(15, 15, 15))
        );
        yoneticiEkranIzinistekleriDialogLayout.setVerticalGroup(
            yoneticiEkranIzinistekleriDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, yoneticiEkranIzinistekleriDialogLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(29, 29, 29)
                .addGroup(yoneticiEkranIzinistekleriDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(yoneticiEkranIzinistekleriDialogLayout.createSequentialGroup()
                        .addComponent(yoneticiEkranIzinistekleriOnaylaButon)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(yoneticiEkranIzinistekleriReddetButon)))
                .addContainerGap(77, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Hoş geldiniz, bla bla bla...");

        jLabel2.setText("İsim : bla bla");

        jLabel3.setText("Soyisim : bla bla");

        jLabel4.setText("Kullanıcı Adı :");

        yoneticiEkranCikisGeriButon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resimler/exiticon.png_48x48.png"))); // NOI18N
        yoneticiEkranCikisGeriButon.setText("Çıkış Yap");
        yoneticiEkranCikisGeriButon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yoneticiEkranCikisGeriButonActionPerformed(evt);
            }
        });

        jMenu1.setText("Listele");

        yoneticiEkranTumKullanicilarMenu.setText("Tüm Kullanıcılar");
        yoneticiEkranTumKullanicilarMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yoneticiEkranTumKullanicilarMenuActionPerformed(evt);
            }
        });
        jMenu1.add(yoneticiEkranTumKullanicilarMenu);

        yoneticiEkranEskiIzinlerMenu.setText("Eski İzinler");
        yoneticiEkranEskiIzinlerMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yoneticiEkranEskiIzinlerMenuActionPerformed(evt);
            }
        });
        jMenu1.add(yoneticiEkranEskiIzinlerMenu);

        yoneticiEkranizinIstekleriMenu.setText("İzin istekleri");
        yoneticiEkranizinIstekleriMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yoneticiEkranizinIstekleriMenuActionPerformed(evt);
            }
        });
        jMenu1.add(yoneticiEkranizinIstekleriMenu);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel3)
                        .addComponent(jLabel2)
                        .addComponent(jLabel4))
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 295, Short.MAX_VALUE)
                .addComponent(yoneticiEkranCikisGeriButon)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(yoneticiEkranCikisGeriButon)))
                .addGap(72, 72, 72)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addContainerGap(223, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void yoneticiEkranCikisGeriButonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yoneticiEkranCikisGeriButonActionPerformed
        AcilisFrame1 aa=new AcilisFrame1();
        aa.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_yoneticiEkranCikisGeriButonActionPerformed

    private void yoneticiEkranTumKullanicilarMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yoneticiEkranTumKullanicilarMenuActionPerformed
        yoneticiEkranTumKullanicilarDialog.setVisible(true);
        
        ///tüm kullanıcıları çek açılır açılmaz...
        Kullanici kullaniciCekme=new Kullanici();
        model=kullaniciCekme.tumKullanicilariGetir();
        
        yoneticiEkranTumKullaniciDialogTablo.setModel(model);
    }//GEN-LAST:event_yoneticiEkranTumKullanicilarMenuActionPerformed

    private void yoneticiEkranEskiIzinlerMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yoneticiEkranEskiIzinlerMenuActionPerformed
        yoneticiEkranEskiizinlerDialog.setVisible(true);
        
        IzinIstek eskiIzinleriListeleyici=new IzinIstek();
        
        /*
        ArrayList<String> filtreler=new ArrayList<String>();
        
        if(yoneticiEkranEskiizinlerDialogIzinYillikFiltre.isSelected())
            filtreler.add(yoneticiEkranEskiizinlerDialogIzinYillikFiltre.getText());
        
        */
        
        model=eskiIzinleriListeleyici.eskiIzinleriListele();
        yoneticiEkranEskiizinlerDialogizinTablo.setModel(model);
        
        
        
    }//GEN-LAST:event_yoneticiEkranEskiIzinlerMenuActionPerformed

    private void yoneticiEkranizinIstekleriMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yoneticiEkranizinIstekleriMenuActionPerformed
        yoneticiEkranIzinistekleriDialog.setVisible(true);
        
        //tüm izin isteklerini çekme...
        IzinIstek izinIstekCekme=new IzinIstek();
        model=izinIstekCekme.tumIzinIstekleriniGetir();
        
        yoneticiEkranIzinistekleriTablo.setModel(model);
        
    }//GEN-LAST:event_yoneticiEkranizinIstekleriMenuActionPerformed

    private void yoneticiEkranIzinistekleriTabloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_yoneticiEkranIzinistekleriTabloMouseClicked
        yoneticiEkranIzinistekleriOnaylaButon.setEnabled(true);
        yoneticiEkranIzinistekleriReddetButon.setEnabled(true);
    }//GEN-LAST:event_yoneticiEkranIzinistekleriTabloMouseClicked

    private void yoneticiEkranIzinistekleriDialogMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_yoneticiEkranIzinistekleriDialogMouseClicked
        yoneticiEkranIzinistekleriOnaylaButon.setEnabled(false);
        yoneticiEkranIzinistekleriReddetButon.setEnabled(false);
    }//GEN-LAST:event_yoneticiEkranIzinistekleriDialogMouseClicked

    private void yoneticiEkranTumKullaniciDialogAramaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yoneticiEkranTumKullaniciDialogAramaButtonActionPerformed
        String filtre=yoneticiEkranTumKullaniciDialogAramatxt.getText();
        Kullanici filtreliKullaniciCekme=new Kullanici();
        model=filtreliKullaniciCekme.adSoyadTumKullanicilariListele(filtre);
        
        yoneticiEkranTumKullaniciDialogTablo.setModel(model);
    }//GEN-LAST:event_yoneticiEkranTumKullaniciDialogAramaButtonActionPerformed

    private void yoneticiEkranIzinistekleriOnaylaButonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yoneticiEkranIzinistekleriOnaylaButonActionPerformed
       int secilenRow=yoneticiEkranIzinistekleriTablo.getSelectedRow();
       String gidenIstekNo=model.getValueAt(secilenRow, 0).toString(); //TABLODA TIKLADIĞIMIZ SATIRIN 0. İNDİSİNİ YANİ istek noSİNİ ALDIM
       //BUNU izinistekteki metoda yolla ve bu istek noya ye ait olan istek durumunu güncelleyip
       //istek durumunu onay yapıp izin tablosuna ekle(eski izinler)
       //   ayrıca onayladıktan sonra kullanıcı tablosundaki kalan izin gününü de düş...
       //
       
        
        boolean durum=false;
        int secim=JOptionPane.showConfirmDialog(this, "Bu izin isteğini onaylamak istediğinize emin misiniz?", "Onay", JOptionPane.OK_CANCEL_OPTION);
        if(secim==0) //eğer izin onaylanırsa..
        {
            IzinIstek izinOnayi=new IzinIstek();
            durum=izinOnayi.istegiOnayla(gidenIstekNo);
            if(durum)
                JOptionPane.showConfirmDialog(this, "Seçim onaylandı.","onay",JOptionPane.OK_OPTION);
            else
                JOptionPane.showConfirmDialog(rootPane, "Hata, kontrol edin.");
                
        }
    
    }//GEN-LAST:event_yoneticiEkranIzinistekleriOnaylaButonActionPerformed

    private void yoneticiEkranIzinistekleriReddetButonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yoneticiEkranIzinistekleriReddetButonActionPerformed
        int secilenRow=yoneticiEkranIzinistekleriTablo.getSelectedRow();
       String gidenIstekNo=model.getValueAt(secilenRow, 0).toString(); 
       
        boolean durum=false;
        int secim=JOptionPane.showConfirmDialog(this, "Bu izin isteğini reddetmek istediğinize emin misiniz?", "Red", JOptionPane.OK_CANCEL_OPTION);
        if(secim==0) //eğer izin reddedilirse..
        {
            IzinIstek izinRed=new IzinIstek();
            durum=izinRed.istegiReddet(gidenIstekNo);
            if(durum)
                JOptionPane.showConfirmDialog(this, "Seçim onaylandı.","onay",JOptionPane.OK_OPTION);
            else
                JOptionPane.showConfirmDialog(rootPane, "Hata, kontrol edin.");
                
        }
    }//GEN-LAST:event_yoneticiEkranIzinistekleriReddetButonActionPerformed

    private void yoneticiEkranEskiizinlerDialogizinAraButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yoneticiEkranEskiizinlerDialogizinAraButtonActionPerformed
                IzinIstek eskiIzinleriFiltreliListeleyici=new IzinIstek();
        
        
        ArrayList<String> filtreler=new ArrayList<String>(); //4 çeşit filtreden seçili olanları eklemesi için..
        
        filtreler.clear();
        
        if(yoneticiEkranEskiizinlerDialogIzinYillikFiltre.isSelected())
            filtreler.add(yoneticiEkranEskiizinlerDialogIzinYillikFiltre.getText());
        if(yoneticiEkranEskiizinlerDialogIzinMazeretFiltre.isSelected())
            filtreler.add(yoneticiEkranEskiizinlerDialogIzinMazeretFiltre.getText());
        if(yoneticiEkranEskiizinlerDialogIzinRaporFiltre.isSelected())
            filtreler.add(yoneticiEkranEskiizinlerDialogIzinRaporFiltre.getText());
        if(yoneticiEkranEskiizinlerDialogIzinUcretsizFiltre.isSelected())
            filtreler.add(yoneticiEkranEskiizinlerDialogIzinUcretsizFiltre.getText());
        
        if(filtreler.size()<1)
        {
            //eğer filtre yoksa tabloyu filtresiz bi şekilde tüm eski izinler ile doldur.
            model=eskiIzinleriFiltreliListeleyici.eskiIzinleriListele();
            yoneticiEkranEskiizinlerDialogizinTablo.setModel(model);
        }
        else
        {
        
        
        model=eskiIzinleriFiltreliListeleyici.eskiIzinleriFiltreliListele(filtreler);
        yoneticiEkranEskiizinlerDialogizinTablo.setModel(model);
        }
    }//GEN-LAST:event_yoneticiEkranEskiizinlerDialogizinAraButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(YoneticiEkran6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(YoneticiEkran6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(YoneticiEkran6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(YoneticiEkran6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new YoneticiEkran6().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton yoneticiEkranCikisGeriButon;
    private javax.swing.JMenuItem yoneticiEkranEskiIzinlerMenu;
    private javax.swing.JDialog yoneticiEkranEskiizinlerDialog;
    private javax.swing.JCheckBox yoneticiEkranEskiizinlerDialogIzinMazeretFiltre;
    private javax.swing.JCheckBox yoneticiEkranEskiizinlerDialogIzinRaporFiltre;
    private javax.swing.JCheckBox yoneticiEkranEskiizinlerDialogIzinUcretsizFiltre;
    private javax.swing.JCheckBox yoneticiEkranEskiizinlerDialogIzinYillikFiltre;
    private javax.swing.JButton yoneticiEkranEskiizinlerDialogizinAraButton;
    private javax.swing.JTable yoneticiEkranEskiizinlerDialogizinTablo;
    private javax.swing.JDialog yoneticiEkranIzinistekleriDialog;
    private javax.swing.JButton yoneticiEkranIzinistekleriOnaylaButon;
    private javax.swing.JButton yoneticiEkranIzinistekleriReddetButon;
    private javax.swing.JTable yoneticiEkranIzinistekleriTablo;
    private javax.swing.JButton yoneticiEkranTumKullaniciDialogAramaButton;
    private javax.swing.JTextField yoneticiEkranTumKullaniciDialogAramatxt;
    private javax.swing.JTable yoneticiEkranTumKullaniciDialogTablo;
    private javax.swing.JDialog yoneticiEkranTumKullanicilarDialog;
    private javax.swing.JMenuItem yoneticiEkranTumKullanicilarMenu;
    private javax.swing.JMenuItem yoneticiEkranizinIstekleriMenu;
    // End of variables declaration//GEN-END:variables
}
