/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author Ridvan
 */
public class YoneticiEkran6 extends javax.swing.JFrame {

    /**
     * Creates new form YoneticiEkran6
     */
    public YoneticiEkran6() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        yoneticiEkranTumKullanicilarDialog = new javax.swing.JDialog();
        jScrollPane1 = new javax.swing.JScrollPane();
        yoneticiEkranTumKullaniciDialogTablo = new javax.swing.JTable();
        yoneticiEkranTumKullaniciDialogAramaButton = new javax.swing.JButton();
        yoneticiEkranTumKullaniciDialogAramatxt = new javax.swing.JTextField();
        yoneticiEkranEskiizinlerDialog = new javax.swing.JDialog();
        jScrollPane2 = new javax.swing.JScrollPane();
        yoneticiEkranEskiizinlerDialogizinTablo = new javax.swing.JTable();
        yoneticiEkranEskiizinlerDialogizinAraButton = new javax.swing.JButton();
        yoneticiEkranEskiizinlerDialogizinAramaGirisTxt = new javax.swing.JTextField();
        yoneticiEkranEskiizinlerDialogIzinYillikFiltre = new javax.swing.JCheckBox();
        yoneticiEkranEskiizinlerDialogIzinMazeretFiltre = new javax.swing.JCheckBox();
        yoneticiEkranEskiizinlerDialogIzinRaporFiltre = new javax.swing.JCheckBox();
        yoneticiEkranEskiizinlerDialogIzinUcretsizFiltre = new javax.swing.JCheckBox();
        yoneticiEkranIzinistekleriDialog = new javax.swing.JDialog();
        jScrollPane3 = new javax.swing.JScrollPane();
        yoneticiEkranIzinistekleriTablo = new javax.swing.JTable();
        yoneticiEkranIzinistekleriOnaylaButon = new javax.swing.JButton();
        yoneticiEkranIzinistekleriReddetButon = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        yoneticiEkranCikisGeriButon = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        yoneticiEkranTumKullanicilarMenu = new javax.swing.JMenuItem();
        yoneticiEkranEskiIzinlerMenu = new javax.swing.JMenuItem();
        yoneticiEkranizinIstekleriMenu = new javax.swing.JMenuItem();

        yoneticiEkranTumKullanicilarDialog.setMinimumSize(new java.awt.Dimension(598, 494));

        yoneticiEkranTumKullaniciDialogTablo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(yoneticiEkranTumKullaniciDialogTablo);

        yoneticiEkranTumKullaniciDialogAramaButton.setText("Kullanıcı Ara");

        javax.swing.GroupLayout yoneticiEkranTumKullanicilarDialogLayout = new javax.swing.GroupLayout(yoneticiEkranTumKullanicilarDialog.getContentPane());
        yoneticiEkranTumKullanicilarDialog.getContentPane().setLayout(yoneticiEkranTumKullanicilarDialogLayout);
        yoneticiEkranTumKullanicilarDialogLayout.setHorizontalGroup(
            yoneticiEkranTumKullanicilarDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, yoneticiEkranTumKullanicilarDialogLayout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(yoneticiEkranTumKullanicilarDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(yoneticiEkranTumKullanicilarDialogLayout.createSequentialGroup()
                        .addComponent(yoneticiEkranTumKullaniciDialogAramatxt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(yoneticiEkranTumKullaniciDialogAramaButton)
                        .addGap(6, 6, 6))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 566, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );
        yoneticiEkranTumKullanicilarDialogLayout.setVerticalGroup(
            yoneticiEkranTumKullanicilarDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, yoneticiEkranTumKullanicilarDialogLayout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addGroup(yoneticiEkranTumKullanicilarDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yoneticiEkranTumKullaniciDialogAramatxt, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yoneticiEkranTumKullaniciDialogAramaButton))
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77))
        );

        yoneticiEkranEskiizinlerDialog.setMinimumSize(new java.awt.Dimension(586, 463));

        yoneticiEkranEskiizinlerDialogizinTablo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(yoneticiEkranEskiizinlerDialogizinTablo);

        yoneticiEkranEskiizinlerDialogizinAraButton.setText("İzin Ara");

        yoneticiEkranEskiizinlerDialogIzinYillikFiltre.setText("Yıllık");

        yoneticiEkranEskiizinlerDialogIzinMazeretFiltre.setText("Mazeret");

        yoneticiEkranEskiizinlerDialogIzinRaporFiltre.setText("Rapor");

        yoneticiEkranEskiizinlerDialogIzinUcretsizFiltre.setText("Ücretsiz");

        javax.swing.GroupLayout yoneticiEkranEskiizinlerDialogLayout = new javax.swing.GroupLayout(yoneticiEkranEskiizinlerDialog.getContentPane());
        yoneticiEkranEskiizinlerDialog.getContentPane().setLayout(yoneticiEkranEskiizinlerDialogLayout);
        yoneticiEkranEskiizinlerDialogLayout.setHorizontalGroup(
            yoneticiEkranEskiizinlerDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, yoneticiEkranEskiizinlerDialogLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(yoneticiEkranEskiizinlerDialogizinAramaGirisTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(yoneticiEkranEskiizinlerDialogizinAraButton)
                .addGap(20, 20, 20))
            .addGroup(yoneticiEkranEskiizinlerDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(yoneticiEkranEskiizinlerDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 566, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(yoneticiEkranEskiizinlerDialogLayout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(yoneticiEkranEskiizinlerDialogIzinYillikFiltre)
                        .addGap(53, 53, 53)
                        .addComponent(yoneticiEkranEskiizinlerDialogIzinMazeretFiltre)
                        .addGap(54, 54, 54)
                        .addComponent(yoneticiEkranEskiizinlerDialogIzinRaporFiltre)
                        .addGap(37, 37, 37)
                        .addComponent(yoneticiEkranEskiizinlerDialogIzinUcretsizFiltre)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        yoneticiEkranEskiizinlerDialogLayout.setVerticalGroup(
            yoneticiEkranEskiizinlerDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, yoneticiEkranEskiizinlerDialogLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(yoneticiEkranEskiizinlerDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yoneticiEkranEskiizinlerDialogizinAramaGirisTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yoneticiEkranEskiizinlerDialogizinAraButton))
                .addGap(27, 27, 27)
                .addGroup(yoneticiEkranEskiizinlerDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yoneticiEkranEskiizinlerDialogIzinYillikFiltre)
                    .addComponent(yoneticiEkranEskiizinlerDialogIzinMazeretFiltre)
                    .addComponent(yoneticiEkranEskiizinlerDialogIzinRaporFiltre)
                    .addComponent(yoneticiEkranEskiizinlerDialogIzinUcretsizFiltre))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        yoneticiEkranIzinistekleriDialog.setMinimumSize(new java.awt.Dimension(663, 461));
        yoneticiEkranIzinistekleriDialog.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                yoneticiEkranIzinistekleriDialogMouseClicked(evt);
            }
        });

        yoneticiEkranIzinistekleriTablo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        yoneticiEkranIzinistekleriTablo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                yoneticiEkranIzinistekleriTabloMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(yoneticiEkranIzinistekleriTablo);

        yoneticiEkranIzinistekleriOnaylaButon.setText("Onayla");
        yoneticiEkranIzinistekleriOnaylaButon.setEnabled(false);

        yoneticiEkranIzinistekleriReddetButon.setText("Reddet");
        yoneticiEkranIzinistekleriReddetButon.setEnabled(false);

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel5.setText("İzin istekleri");

        javax.swing.GroupLayout yoneticiEkranIzinistekleriDialogLayout = new javax.swing.GroupLayout(yoneticiEkranIzinistekleriDialog.getContentPane());
        yoneticiEkranIzinistekleriDialog.getContentPane().setLayout(yoneticiEkranIzinistekleriDialogLayout);
        yoneticiEkranIzinistekleriDialogLayout.setHorizontalGroup(
            yoneticiEkranIzinistekleriDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, yoneticiEkranIzinistekleriDialogLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(250, 250, 250))
            .addGroup(yoneticiEkranIzinistekleriDialogLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66)
                .addGroup(yoneticiEkranIzinistekleriDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(yoneticiEkranIzinistekleriOnaylaButon)
                    .addComponent(yoneticiEkranIzinistekleriReddetButon))
                .addContainerGap(89, Short.MAX_VALUE))
        );
        yoneticiEkranIzinistekleriDialogLayout.setVerticalGroup(
            yoneticiEkranIzinistekleriDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, yoneticiEkranIzinistekleriDialogLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addGroup(yoneticiEkranIzinistekleriDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(yoneticiEkranIzinistekleriDialogLayout.createSequentialGroup()
                        .addComponent(yoneticiEkranIzinistekleriOnaylaButon)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(yoneticiEkranIzinistekleriReddetButon))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Hoş geldiniz, bla bla bla...");

        jLabel2.setText("İsim : bla bla");

        jLabel3.setText("Soyisim : bla bla");

        jLabel4.setText("Kullanıcı Adı :");

        yoneticiEkranCikisGeriButon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resimler/exiticon.png_48x48.png"))); // NOI18N
        yoneticiEkranCikisGeriButon.setText("Çıkış Yap");
        yoneticiEkranCikisGeriButon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yoneticiEkranCikisGeriButonActionPerformed(evt);
            }
        });

        jMenu1.setText("Listele");

        yoneticiEkranTumKullanicilarMenu.setText("Tüm Kullanıcılar");
        yoneticiEkranTumKullanicilarMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yoneticiEkranTumKullanicilarMenuActionPerformed(evt);
            }
        });
        jMenu1.add(yoneticiEkranTumKullanicilarMenu);

        yoneticiEkranEskiIzinlerMenu.setText("Eski İzinler");
        yoneticiEkranEskiIzinlerMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yoneticiEkranEskiIzinlerMenuActionPerformed(evt);
            }
        });
        jMenu1.add(yoneticiEkranEskiIzinlerMenu);

        yoneticiEkranizinIstekleriMenu.setText("İzin istekleri");
        yoneticiEkranizinIstekleriMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yoneticiEkranizinIstekleriMenuActionPerformed(evt);
            }
        });
        jMenu1.add(yoneticiEkranizinIstekleriMenu);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel3)
                        .addComponent(jLabel2)
                        .addComponent(jLabel4))
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 295, Short.MAX_VALUE)
                .addComponent(yoneticiEkranCikisGeriButon)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(yoneticiEkranCikisGeriButon)))
                .addGap(72, 72, 72)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addContainerGap(223, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void yoneticiEkranCikisGeriButonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yoneticiEkranCikisGeriButonActionPerformed
        AcilisFrame1 aa=new AcilisFrame1();
        aa.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_yoneticiEkranCikisGeriButonActionPerformed

    private void yoneticiEkranTumKullanicilarMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yoneticiEkranTumKullanicilarMenuActionPerformed
        yoneticiEkranTumKullanicilarDialog.setVisible(true);
    }//GEN-LAST:event_yoneticiEkranTumKullanicilarMenuActionPerformed

    private void yoneticiEkranEskiIzinlerMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yoneticiEkranEskiIzinlerMenuActionPerformed
        yoneticiEkranEskiizinlerDialog.setVisible(true);
    }//GEN-LAST:event_yoneticiEkranEskiIzinlerMenuActionPerformed

    private void yoneticiEkranizinIstekleriMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yoneticiEkranizinIstekleriMenuActionPerformed
        yoneticiEkranIzinistekleriDialog.setVisible(true);
    }//GEN-LAST:event_yoneticiEkranizinIstekleriMenuActionPerformed

    private void yoneticiEkranIzinistekleriTabloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_yoneticiEkranIzinistekleriTabloMouseClicked
        yoneticiEkranIzinistekleriOnaylaButon.setEnabled(true);
        yoneticiEkranIzinistekleriReddetButon.setEnabled(true);
    }//GEN-LAST:event_yoneticiEkranIzinistekleriTabloMouseClicked

    private void yoneticiEkranIzinistekleriDialogMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_yoneticiEkranIzinistekleriDialogMouseClicked
        yoneticiEkranIzinistekleriOnaylaButon.setEnabled(false);
        yoneticiEkranIzinistekleriReddetButon.setEnabled(false);
    }//GEN-LAST:event_yoneticiEkranIzinistekleriDialogMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(YoneticiEkran6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(YoneticiEkran6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(YoneticiEkran6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(YoneticiEkran6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new YoneticiEkran6().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton yoneticiEkranCikisGeriButon;
    private javax.swing.JMenuItem yoneticiEkranEskiIzinlerMenu;
    private javax.swing.JDialog yoneticiEkranEskiizinlerDialog;
    private javax.swing.JCheckBox yoneticiEkranEskiizinlerDialogIzinMazeretFiltre;
    private javax.swing.JCheckBox yoneticiEkranEskiizinlerDialogIzinRaporFiltre;
    private javax.swing.JCheckBox yoneticiEkranEskiizinlerDialogIzinUcretsizFiltre;
    private javax.swing.JCheckBox yoneticiEkranEskiizinlerDialogIzinYillikFiltre;
    private javax.swing.JButton yoneticiEkranEskiizinlerDialogizinAraButton;
    private javax.swing.JTextField yoneticiEkranEskiizinlerDialogizinAramaGirisTxt;
    private javax.swing.JTable yoneticiEkranEskiizinlerDialogizinTablo;
    private javax.swing.JDialog yoneticiEkranIzinistekleriDialog;
    private javax.swing.JButton yoneticiEkranIzinistekleriOnaylaButon;
    private javax.swing.JButton yoneticiEkranIzinistekleriReddetButon;
    private javax.swing.JTable yoneticiEkranIzinistekleriTablo;
    private javax.swing.JButton yoneticiEkranTumKullaniciDialogAramaButton;
    private javax.swing.JTextField yoneticiEkranTumKullaniciDialogAramatxt;
    private javax.swing.JTable yoneticiEkranTumKullaniciDialogTablo;
    private javax.swing.JDialog yoneticiEkranTumKullanicilarDialog;
    private javax.swing.JMenuItem yoneticiEkranTumKullanicilarMenu;
    private javax.swing.JMenuItem yoneticiEkranizinIstekleriMenu;
    // End of variables declaration//GEN-END:variables
}
